#!/bin/bash

echo "=== DÉPLOIEMENT RAILWAY GPCM ==="
echo ""
echo "📋 CHECKLIST AVANT DÉPLOIEMENT:"
echo ""
echo "1. ✅ API Météo corrigée - Utilise l'API forecast standard (compatible avec tous les comptes)"
echo "2. ✅ Images de maillots - Utilisation du répertoire local (pas de volume)"
echo "3. ✅ railway.json mis à jour - Suppression de CMS_JERSEYS_DIR"
echo "4. ✅ Votre clé API OpenWeather configurée avec support des volumes élevés"
echo ""
echo "📌 VARIABLES D'ENVIRONNEMENT OPTIONNELLES SUR RAILWAY:"
echo "   - OPENWEATHER_API_KEY = 27fd496c6cc9c8cd6f8981bf682c5dd4 (optionnel)"
echo "   - CMS_USER = admin (déjà par défaut)"
echo "   - CMS_PASS = Axelle20 (déjà par défaut)"
echo ""
echo "🚀 COMMANDES DE DÉPLOIEMENT:"
echo ""
echo "   git add -A"
echo "   git commit -m 'Fix: API météo et chemins des maillots pour Railway'"
echo "   git push origin main"
echo ""
echo "Railway va automatiquement:"
echo "  - Détecter le push sur main"
echo "  - Construire avec npm install"
echo "  - Démarrer avec npm start"
echo ""
echo "📊 APRÈS DÉPLOIEMENT:"
echo "  - Vérifier: https://[votre-app].up.railway.app/api/weather/current?lat=45.5019&lon=-73.5674&units=metric&lang=fr"
echo "  - Vérifier: https://[votre-app].up.railway.app/images/jerseys/jersey-1757184966447-260600803.png"
echo ""
echo "✨ Les corrections appliquées:"
echo "  1. Clé API OpenWeather par défaut dans server.js"
echo "  2. Chemins des maillots simplifiés (./images/jerseys)"
echo "  3. Suppression du volume /data non nécessaire"
