[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "npm start"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 3
  healthcheckPath = "/health"
  healthcheckTimeout = 300
  region = "us-east"

[environments.production]
  NODE_ENV = "production"
  PORT = 3000
  DB_POOL_MAX = 20
  DB_POOL_IDLE_MS = 30000
  DB_POOL_CONN_MS = 5000
  # Cluster tuning
  WORKERS = "max" # or set a number up to 32
  UV_THREADPOOL_SIZE = 64
  # Keep-Alive for many concurrent sockets
  NODE_OPTIONS = "--max-old-space-size=28672 --heapsnapshot-near-heap-limit=1 --enable-source-maps"
  # Uncomment and set if using Postgres
  # DB_TYPE = "postgres"
  # DATABASE_URL = "postgresql://user:pass@host:5432/dbname"
  # DB_SSL = "1"

